In [1]:
import pandas as pd
from scipy.stats import poisson
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
# merging four csv files_2012
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2012/2012Q1-capitalbikeshare-tripdata.csv', './Resources/Washington DC/2012/2012Q2-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2012/2012Q3-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2012/2012Q4-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,475,2012-01-01 00:04:00,2012-01-01 00:11:56,31245,7th & R St NW / Shaw Library,31109,7th & T St NW,W01412,Member
1,1162,2012-01-01 00:10:05,2012-01-01 00:29:28,31400,Georgia & New Hampshire Ave NW,31103,16th & Harvard St NW,W00524,Casual
2,1145,2012-01-01 00:10:23,2012-01-01 00:29:28,31400,Georgia & New Hampshire Ave NW,31103,16th & Harvard St NW,W00235,Member
3,485,2012-01-01 00:15:41,2012-01-01 00:23:46,31101,14th & V St NW,31602,Park Rd & Holmead Pl NW,W00864,Member
4,471,2012-01-01 00:15:42,2012-01-01 00:23:34,31102,11th & Kenyon St NW,31109,7th & T St NW,W00995,Member
...,...,...,...,...,...,...,...,...,...
2028906,8630,2012-12-31 23:51:38,2013-01-01 02:15:29,31619,Lincoln Park / 13th & East Capitol St NE,31619,Lincoln Park / 13th & East Capitol St NE,W00704,Casual
2028907,418,2012-12-31 23:56:19,2013-01-01 00:03:17,31101,14th & V St NW,31200,Massachusetts Ave & Dupont Circle NW,W00098,Member
2028908,384,2012-12-31 23:56:35,2013-01-01 00:03:00,31101,14th & V St NW,31200,Massachusetts Ave & Dupont Circle NW,W01398,Member
2028909,448,2012-12-31 23:58:20,2013-01-01 00:05:49,31613,Eastern Market Metro / Pennsylvania Ave & 7th ...,31607,14th & D St SE,W01301,Member
2028910,251,2012-12-31 23:59:23,2013-01-01 00:03:34,31223,Convention Center / 7th & M St NW,31241,Thomas Circle,W01460,Member

In [3]:
#Exporting the 2012 merged file in to csv
df.to_csv('./Resources/2012_citibike.csv', index=False)

In [4]:
# merging four quarterly csv files year 2013
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2013/2013Q1-capitalbikeshare-tripdata.csv', './Resources/Washington DC/2013/2013Q2-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2013/2013Q3-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2013/2013Q4-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,688,2013-01-01 00:03:55,2013-01-01 00:15:24,31101,14th & V St NW,31106,Calvert & Biltmore St NW,W01210,Member
1,699,2013-01-01 00:04:39,2013-01-01 00:16:19,31236,37th & O St NW / Georgetown University,31304,36th & Calvert St NW / Glover Park,W01075,Member
2,365,2013-01-01 00:10:01,2013-01-01 00:16:06,31257,22nd & I St NW / Foggy Bottom,31239,Rhode Island & Connecticut Ave NW,w00527,Member
3,292,2013-01-01 00:12:55,2013-01-01 00:17:47,31614,11th & H St NE,31612,D St & Maryland Ave NE,W00040,Member
4,222,2013-01-01 00:13:24,2013-01-01 00:17:07,31239,Rhode Island & Connecticut Ave NW,31214,17th & Corcoran St NW,W20891,Member
...,...,...,...,...,...,...,...,...,...
2555536,1571,2013-12-31 23:53:07,2014-01-01 00:19:19,31244,4th & E St SW,31271,Constitution Ave & 2nd St NW/DOL,W20384,Member
2555537,1564,2013-12-31 23:53:27,2014-01-01 00:19:31,31244,4th & E St SW,31271,Constitution Ave & 2nd St NW/DOL,W00319,Member
2555538,1687,2013-12-31 23:54:58,2014-01-01 00:23:06,31015,Rosslyn Metro / Wilson Blvd & Ft Myer Dr,31015,Rosslyn Metro / Wilson Blvd & Ft Myer Dr,W01038,Casual
2555539,1583,2013-12-31 23:56:50,2014-01-01 00:23:13,31015,Rosslyn Metro / Wilson Blvd & Ft Myer Dr,31015,Rosslyn Metro / Wilson Blvd & Ft Myer Dr,W00020,Casual
2555540,474,2013-12-31 23:58:19,2014-01-01 00:06:13,31222,New York Ave & 15th St NW,31260,23rd & E St NW,W01407,Member

In [5]:
#Exporting the 2013 merged file in to csv
df.to_csv('./Resources/2013_citibike.csv', index=False)

In [6]:
# merging four quarterly csv files year 2014
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2014/2014Q1-capitalbikeshare-tripdata.csv', './Resources/Washington DC/2014/2014Q2-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2014/2014Q3-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2014/2014Q4-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,1716,2014-01-01 00:06:03,2014-01-01 00:34:40,31102,11th & Kenyon St NW,31632,15th & F St NE,W01363,Member
1,154,2014-01-01 00:11:09,2014-01-01 00:13:43,31602,Park Rd & Holmead Pl NW,31107,Lamont & Mt Pleasant NW,W01433,Member
2,318,2014-01-01 00:12:19,2014-01-01 00:17:38,31223,Convention Center / 7th & M St NW,31509,New Jersey Ave & R St NW,W00065,Member
3,480,2014-01-01 00:14:02,2014-01-01 00:22:02,31203,14th & Rhode Island Ave NW,31109,7th & T St NW,W20903,Member
4,345,2014-01-01 00:15:33,2014-01-01 00:21:18,31241,Thomas Circle,31600,5th & K St NW,W20888,Member
...,...,...,...,...,...,...,...,...,...
2913145,572,2014-12-31 23:45:46,2014-12-31 23:55:19,31239,Rhode Island & Connecticut Ave NW,31268,12th & U St NW,W21648,Member
2913146,433,2014-12-31 23:46:52,2014-12-31 23:54:05,31508,Gallaudet / 8th St & Florida Ave NE,31600,5th & K St NW,W00283,Member
2913147,1922,2014-12-31 23:48:01,2015-01-01 00:20:03,31249,Jefferson Memorial,31249,Jefferson Memorial,W01244,Member
2913148,557,2014-12-31 23:48:16,2014-12-31 23:57:34,31220,US Dept of State / Virginia Ave & 21st St NW,31258,Lincoln Memorial,W21494,Casual
2913149,595,2014-12-31 23:59:14,2015-01-01 00:09:10,31221,18th & M St NW,31114,18th St & Wyoming Ave NW,W01270,Member

In [7]:
#Exporting the 2014 merged file in to csv
df.to_csv('./Resources/2014_citibike.csv', index=False)

In [8]:
# merging four quarterly csv files year 2015
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2015/2015Q1-capitalbikeshare-tripdata.csv', './Resources/Washington DC/2015/2015Q2-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2015/2015Q3-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2015/2015Q4-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,2389,2015-01-01 00:02:44,2015-01-01 00:42:33,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W01140,Casual
1,2394,2015-01-01 00:02:46,2015-01-01 00:42:41,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W00612,Casual
2,468,2015-01-01 00:04:32,2015-01-01 00:12:20,31204,20th & E St NW,31234,20th & O St NW / Dupont South,W01226,Member
3,348,2015-01-01 00:07:18,2015-01-01 00:13:06,31602,Park Rd & Holmead Pl NW,31117,15th & Euclid St NW,W20216,Member
4,980,2015-01-01 00:09:39,2015-01-01 00:26:00,31247,Jefferson Dr & 14th St SW,31241,Thomas Circle,W21005,Casual
...,...,...,...,...,...,...,...,...,...
3185901,1439,2015-12-31 23:53:01,2016-01-01 00:17:01,31051,Arlington Blvd & N Queen St,31258,Lincoln Memorial,W20756,Member
3185902,1440,2015-12-31 23:53:03,2016-01-01 00:17:04,31051,Arlington Blvd & N Queen St,31258,Lincoln Memorial,W20374,Member
3185903,455,2015-12-31 23:56:46,2016-01-01 00:04:22,31114,18th St & Wyoming Ave NW,31280,11th & S St NW,W21538,Member
3185904,820,2015-12-31 23:57:46,2016-01-01 00:11:27,31226,34th St & Wisconsin Ave NW,31214,17th & Corcoran St NW,W22194,Member
3185905,244,2015-12-31 23:57:57,2016-01-01 00:02:01,31628,1st & K St SE,31108,4th & M St SW,W00589,Member

In [9]:
#Exporting the 2015 merged file in to csv
df.to_csv('./Resources/2015_citibike.csv', index=False)

In [10]:
# merging four quarterly csv files year 
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2016/2016Q1-capitalbikeshare-tripdata.csv', './Resources/Washington DC/2016/2016Q2-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2016/2016Q3-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2016/2016Q4-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,166,2016-01-01 00:06:58,2016-01-01 00:09:44,31102,11th & Kenyon St NW,31105,14th & Harvard St NW,W01346,Member
1,448,2016-01-01 00:10:20,2016-01-01 00:17:48,32039,Old Georgetown Rd & Southwick St,32002,Bethesda Ave & Arlington Rd,W22202,Member
2,715,2016-01-01 00:13:52,2016-01-01 00:25:48,31222,New York Ave & 15th St NW,31214,17th & Corcoran St NW,W21427,Member
3,213,2016-01-01 00:15:29,2016-01-01 00:19:03,31506,1st & Rhode Island Ave NW,31509,New Jersey Ave & R St NW,W01294,Member
4,872,2016-01-01 00:16:16,2016-01-01 00:30:49,31041,Prince St & Union St,31048,King St Metro South,W22058,Member
...,...,...,...,...,...,...,...,...,...
3333989,614,2016-12-31 23:49:54,2017-01-01 00:00:09,31118,3rd & Elm St NW,31102,11th & Kenyon St NW,W20961,Member
3333990,483,2016-12-31 23:51:58,2017-01-01 00:00:01,31612,D St & Maryland Ave NE,31628,1st & K St SE,W00381,Member
3333991,438,2016-12-31 23:52:59,2017-01-01 00:00:18,31603,1st & M St NE,31506,1st & Rhode Island Ave NW,W00246,Casual
3333992,1199,2016-12-31 23:53:53,2017-01-01 00:13:53,31249,Jefferson Memorial,31003,15th & Crystal Dr,W23100,Member
3333993,824,2016-12-31 23:54:20,2017-01-01 00:08:05,31232,7th & F St NW / National Portrait Gallery,31290,17th St & Independence Ave SW,W01135,Member

In [11]:
#Exporting the 2016 merged file in to csv
df.to_csv('./Resources/2016_citibike.csv', index=False)

In [12]:
# merging four quarterly csv files year 2017
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2017/2017Q1-capitalbikeshare-tripdata.csv', './Resources/Washington DC/2017/2017Q2-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2017/2017Q3-capitalbikeshare-tripdata.csv','./Resources/Washington DC/2017/2017Q4-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,221,2017-01-01 00:00:41,2017-01-01 00:04:23,31634,3rd & Tingey St SE,31208,M St & New Jersey Ave SE,W00869,Member
1,1676,2017-01-01 00:06:53,2017-01-01 00:34:49,31258,Lincoln Memorial,31270,8th & D St NW,W00894,Casual
2,1356,2017-01-01 00:07:10,2017-01-01 00:29:47,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31222,New York Ave & 15th St NW,W21945,Casual
3,1327,2017-01-01 00:07:22,2017-01-01 00:29:30,31289,Henry Bacon Dr & Lincoln Memorial Circle NW,31222,New York Ave & 15th St NW,W20012,Casual
4,1636,2017-01-01 00:07:36,2017-01-01 00:34:52,31258,Lincoln Memorial,31270,8th & D St NW,W22786,Casual
...,...,...,...,...,...,...,...,...,...
3757772,277,2017-12-31 23:43:17,2017-12-31 23:47:54,31109,7th & T St NW,31118,3rd & Elm St NW,W21036,Member
3757773,399,2017-12-31 23:51:55,2017-12-31 23:58:35,31125,15th & W St NW,31110,20th St & Florida Ave NW,W23147,Casual
3757774,393,2017-12-31 23:55:19,2018-01-01 00:01:52,31209,1st & N St SE,31609,Maine Ave & 7th St SW,W20144,Member
3757775,1319,2017-12-31 23:57:42,2018-01-01 00:19:42,31102,11th & Kenyon St NW,31102,11th & Kenyon St NW,W20860,Member
3757776,266,2017-12-31 23:58:21,2018-01-01 00:02:48,31229,New Hampshire Ave & T St NW,31119,14th & Belmont St NW,W01459,Member

In [13]:
#Exporting the 2017 merged file in to csv
df.to_csv('./Resources/2017_citibike.csv', index=False)

In [22]:
# merging four quarterly csv files year 2014
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2018/201801_capitalbikeshare_tripdata.csv',                       
                      './Resources/Washington DC/2018/201802-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201803-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201804-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201805-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201806-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201807-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201808-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201809-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201810-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201811-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2018/201812-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,552,2018-01-01 00:05:06,2018-01-01 00:14:18,31104,Adams Mill & Columbia Rd NW,31400,Georgia & New Hampshire Ave NW,W00886,Member
1,1282,2018-01-01 00:14:30,2018-01-01 00:35:53,31321,15th St & Constitution Ave NW,31321,15th St & Constitution Ave NW,W01435,Casual
2,1265,2018-01-01 00:14:53,2018-01-01 00:35:58,31321,15th St & Constitution Ave NW,31321,15th St & Constitution Ave NW,W21242,Casual
3,578,2018-01-01 00:15:31,2018-01-01 00:25:09,31406,14th & Upshur St NW,31103,16th & Harvard St NW,W21322,Casual
4,372,2018-01-01 00:18:02,2018-01-01 00:24:15,31618,4th & East Capitol St NE,31619,Lincoln Park / 13th & East Capitol St NE,W00119,Member
...,...,...,...,...,...,...,...,...,...
3542679,3313,2018-12-31 23:37:22,2019-01-01 00:32:36,31615,6th & H St NE,31624,North Capitol St & F St NW,W00159,Member
3542680,888,2018-12-31 23:42:18,2018-12-31 23:57:07,31618,4th & East Capitol St NE,31509,New Jersey Ave & R St NW,W22026,Member
3542681,2332,2018-12-31 23:44:23,2019-01-01 00:23:16,31907,Franklin & S Washington St,32406,Fleet St & Waterfront St,W23900,Member
3542682,307,2018-12-31 23:52:42,2018-12-31 23:57:50,31114,18th St & Wyoming Ave NW,31103,16th & Harvard St NW,W00761,Member
3542683,1062,2018-12-31 23:54:09,2019-01-01 00:11:52,31110,20th St & Florida Ave NW,31014,Lynn & 19th St North,W21324,Member

In [23]:
#Exporting the 2018 merged file in to csv
df.to_csv('./Resources/2018_citibike.csv', index=False)

In [34]:
# merging four quarterly csv files year 2014
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2019/201901-capitalbikeshare-tripdata.csv',                       
                      './Resources/Washington DC/2019/201902-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201903-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201904-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201905-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201906-capitalbikeshare-tripdata.csv',
                      #'./Resources/Washington DC/2019/201907-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201908-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201909-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201910-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201911-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2019/201912-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,230,2019-01-01 00:04:48,2019-01-01 00:08:39,31203,14th & Rhode Island Ave NW,31200,Massachusetts Ave & Dupont Circle NW,E00141,Member
1,1549,2019-01-01 00:06:37,2019-01-01 00:32:27,31321,15th St & Constitution Ave NW,31114,18th St & Wyoming Ave NW,W24067,Casual
2,177,2019-01-01 00:08:46,2019-01-01 00:11:44,31104,Adams Mill & Columbia Rd NW,31323,Woodley Park Metro / Calvert St & Connecticut ...,W22654,Casual
3,228,2019-01-01 00:08:47,2019-01-01 00:12:35,31281,8th & O St NW,31280,11th & S St NW,W22336,Member
4,1300,2019-01-01 00:12:29,2019-01-01 00:34:10,31014,Lynn & 19th St North,31923,Columbia Pike & S Taylor St,70004,Member
...,...,...,...,...,...,...,...,...,...
3041767,130,2019-12-31 23:57:36,2019-12-31 23:59:46,31011,Crystal Dr & 23rd St S,31009,Crystal Dr & 27th St S,W21285,Member
3041768,664,2019-12-31 23:57:47,2020-01-01 00:08:51,31125,15th & W St NW,31281,8th & O St NW,W24197,Member
3041769,389,2019-12-31 23:59:37,2020-01-01 00:06:06,31047,Braddock Rd Metro,31085,Mount Vernon Ave & E Nelson Ave,W21281,Member
3041770,962,2019-12-31 23:59:38,2020-01-01 00:15:40,31236,37th & O St NW / Georgetown University,31214,17th & Corcoran St NW,W00534,Member
3041771,183,2019-12-31 23:59:55,2020-01-01 00:02:58,31227,13th St & New York Ave NW,31254,15th & K St NW,W22782,Member

In [35]:
#Exporting the 2019 merged file in to csv, *we missing month 07 here*!
df.to_csv('./Resources/2019_citibike.csv', index=False)

In [36]:
# merging four quarterly csv files year *we are missing month 04 here*
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2020/202001-capitalbikeshare-tripdata.csv',                       
                      './Resources/Washington DC/2020/202002-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202003-capitalbikeshare-tripdata.csv',
                      #'./Resources/Washington DC/2020/202004-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202005-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202006-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202007-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202008-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202009-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202010-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202011-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2020/202012-capitalbikeshare-tripdata.csv']), ignore_index=True)
df

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,ride_id,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,506.0,2020-01-01 00:00:59,2020-01-01 00:09:26,31623.0,Columbus Circle / Union Station,31658.0,Rosedale Rec Center,W22189,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1050.0,2020-01-01 00:01:16,2020-01-01 00:18:47,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31606.0,Potomac & Pennsylvania Ave SE,W21067,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1687.0,2020-01-01 00:02:42,2020-01-01 00:30:50,31218.0,L'Enfant Plaza / 7th & C St SW,31271.0,Constitution Ave & 2nd St NW/DOL,W24359,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,182.0,2020-01-01 00:02:44,2020-01-01 00:05:47,31627.0,3rd & M St NE,31508.0,Gallaudet / 8th St & Florida Ave NE,W23334,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1002.0,2020-01-01 00:06:12,2020-01-01 00:22:54,31247.0,Jefferson Dr & 14th St SW,31274.0,10th & G St NW,W23441,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2141438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A10ED3D50E5AB612,...,2020-12-12 14:17:02,Jefferson Dr & 14th St SW,31247.0,19th St & Constitution Ave NW,31235.0,38.888553,-77.032427,38.892300,-77.043600,casual
2141439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F146CC9669ABF5EC,...,2020-12-03 14:06:11,Jefferson Dr & 14th St SW,31247.0,4th St & Madison Dr NW,31288.0,38.888553,-77.032427,38.890496,-77.017247,casual
2141440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,614005BC98FE93F7,...,2020-12-06 08:03:46,Jefferson Dr & 14th St SW,31247.0,19th St & Constitution Ave NW,31235.0,38.888552,-77.032427,38.892300,-77.043600,casual
2141441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86783BF38F4567FA,...,2020-12-21 14:26:59,Jefferson Dr & 14th St SW,31247.0,17th & G St NW,31277.0,38.888553,-77.032427,38.898283,-77.039732,casual
2141442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A7F61D67643CB526,...,2020-12-18 09:23:54,New Hampshire Ave & 24th St NW,31275.0,4th St & Madison Dr NW,31288.0,38.901755,-77.051084,38.890496,-77.017246,member

In [37]:
#Exporting the 2013 merged file in to csv, *we missing month 07 here*!
df.to_csv('./Resources/2020_citibike.csv', index=False)

In [33]:
# merging four quarterly csv files year *we are missing month 04 here*
df = pd.concat(
    map(pd.read_csv, ['./Resources/Washington DC/2021/202101-capitalbikeshare-tripdata.csv',                       
                      './Resources/Washington DC/2021/202102-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2021/202103-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2021/202104-capitalbikeshare-tripdata.csv',
                      './Resources/Washington DC/2021/202105-capitalbikeshare-tripdata.csv',
                     ]), ignore_index=True)

SyntaxError: invalid syntax (<ipython-input-33-2e4031e45805>, line 7)